[package]
name = "rabbitmq_http_client"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.2", features = ["derive", "help", "color"] }
thiserror = "1"
sysexits = "0.5.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
