[package]
name = "rabbitmqadmin"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.2", features = ["derive", "help", "color"] }
url = "2"
thiserror = "1"
sysexits = "0.5.0"
rabbitmq_http_client = { path = "../../../rabbitmq-http-api-client-rs.git/" }